# Generated by Django 4.2.30 on 2026-05-10 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('battery_level', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('flying', 'Flying'), ('charging', 'Charging'), ('maintenance', 'Maintenance')], default='ready', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(default='', max_length=255)),
                ('order_content', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('emergency_stop', 'Emergency Stop')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_missions', to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='delivery.drone')),
            ],
        ),
    ]
