# Generated by Django 4.2.30 on 2026-05-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('vkusvill', 'ВкусВилл'), ('magnit', 'Магнит'), ('pyaterochka', 'Пятерочка'), ('lenta', 'Лента')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
