# Generated by Django 4.2.30 on 2026-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_catalogitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='store',
            field=models.CharField(choices=[('vkusvill', 'ВкусВилл'), ('magnit', 'Магнит'), ('pyaterochka', 'Пятерочка'), ('lenta', 'Лента'), ('depo', 'Фудмолл Депо'), ('syrovarnya', 'Сыроварня'), ('white_rabbit', 'White Rabbit'), ('pushkin', 'Кафе Пушкинъ')], max_length=50),
        ),
    ]
